---
ID: "10e865df-ad6a-4df1-8f4b-f8cfaffe7bf0"
Parent: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Template: "ec4dd3f2-590d-404b-9189-2a12679749cc"
Path: /sitecore/templates/Foundation/Dictionary/DictionaryEntry/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180710T094853Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ddacdd55-5b08-405f-9e58-04f09aed640a"
      Hint: Phrase
      Value: $name
